import type { IncomingMessage, ServerResponse } from "node:http";
import { Readable } from "node:stream";

// dist/server/server.js is generated by `npm run build` before Vercel bundles this function
// @ts-expect-error – no type declarations for the compiled server bundle
import server from "../dist/server/server.js";

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const forwardedHost = req.headers["x-forwarded-host"];
  const host =
    (Array.isArray(forwardedHost) ? forwardedHost[0] : forwardedHost) ||
    req.headers.host ||
    "localhost";

  const forwardedProto = req.headers["x-forwarded-proto"];
  const proto = (Array.isArray(forwardedProto) ? forwardedProto[0] : forwardedProto) || "https";

  const url = new URL(req.url!, `${proto}://${host}`);

  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value == null) continue;
    if (Array.isArray(value)) {
      value.forEach((v) => headers.append(key, v));
    } else {
      headers.set(key, value);
    }
  }

  let body: BodyInit | null = null;
  if (req.method !== "GET" && req.method !== "HEAD") {
    const chunks: Buffer[] = [];
    for await (const chunk of req) {
      chunks.push(Buffer.from(chunk as Buffer | string));
    }
    if (chunks.length > 0) {
      body = Buffer.concat(chunks);
    }
  }

  const request = new Request(url, {
    method: req.method,
    headers,
    body,
  });

  const response: Response = await server.fetch(request);

  res.statusCode = response.status;
  for (const [key, value] of response.headers.entries()) {
    res.setHeader(key, value);
  }

  if (response.body) {
    Readable.fromWeb(response.body as Parameters<typeof Readable.fromWeb>[0]).pipe(res);
  } else {
    res.end();
  }
}
